name: Build Mod Packages
on:
  push:
    # new commits are pushed onto these branches
    branches:
      - default
      - 1.20.x
    # OR commits are tagged with version tags
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: minecraft-access # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set Up Gradle
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: wrapper

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@064a97fb0b4cef86a65f09898c572382f3af10e0

      - name: Build Fabric with Gradle
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: build
          build-root-directory: ./fabric

      - name: Build Forge with Gradle
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: build
          build-root-directory: ./forge

      - name: Move and Rename Mod Files
        run: |
          mkdir -p ./upload
          rm ./fabric/build/libs/minecraft-access-*-dev-shadow.jar ./fabric/build/libs/minecraft-access-*-sources.jar
          mv ./fabric/build/libs/minecraft-access*.jar $(basename -s .jar -a *)-fabric.jar
          cp ./fabric/build/libs/minecraft-access*-fabric.jar ./upload
          rm ./forge/build/libs/minecraft-access-*-dev-shadow.jar ./forge/build/libs/minecraft-access-*-sources.jar
          mv ./forge/build/libs/minecraft-access*.jar $(basename -s .jar -a *)-forge.jar
          cp ./forge/build/libs/minecraft-access*-fabric.jar ./upload

      # Then we can download them from workflow result page
      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: ./upload
