# Wrap What's Changed Section of GitHub Releases
# and
# Change Pre-released GitHub Release to Formal Release
name: Post GitHub Release Process

on:
  workflow_call:
    inputs:
      release-tag:
        required: true
        type: string
      pre-release:
        required: true
        type: boolean

env:
  TEMP_BODY_FILE: .release_body

jobs:
  wrap:
    name: Wrap
    runs-on: ubuntu-latest
    # ref: https://stackoverflow.com/questions/67389957/what-permissions-does-github-token-require-for-releases-from-a-github-action
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # github.repository: owner/repo
      # Release API ref: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-a-release-by-tag-name
      #
      # Extract "body" and "id" from API response
      #
      # "body" string contains literally "\r\n"
      # (why windows format? Does GitHub API server is running on windows?)
      # so use sed to replace "\r\n" with new lines
      #
      # There will be multiple matches of "id" and we take first, that's GitHub release id.
      - name: Get Release Body
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.release-tag }} \
          > .temp_response
          
          grep -oP '(?<="body": ").*(?=",)' .temp_response | sed 's/\\r\\n/\n/g' > ${{ env.TEMP_BODY_FILE }}

          echo "RELEASE_ID=$(grep -oP '(?<="id": ).*(?=,)' .temp_response | head -n1)" >> $GITHUB_ENV

      - name: Check If Release Has Been Changed
        id: check
        run: |
          if grep "Auto Generated Release Notes" ${{ env.TEMP_BODY_FILE }} ; then echo "result=true" >> $GITHUB_OUTPUT ; fi

      # Wrap "What's Changed" section with:
      # <details>
      # <summary>Auto Generated Release Notes</summary>
      # <p>
      # ...
      # </p>
      # </details>
      - name: Wrap What's Changed Section
        if: ${{ steps.check.outputs.result != 'true' }}
        run: |
          sed -i "s/^## What's Changed/\<details>\<summary>Auto Generated Release Notes\<\/summary>\<p>\\n## What's Changed\\n/" ${{ env.TEMP_BODY_FILE }}
          printf "\n</p></details>" >> ${{ env.TEMP_BODY_FILE }}

      - name: Apply Changed Release Body to Release
        if: ${{ steps.check.outputs.result != 'true' }}
        # ref: https://github.com/irongut/EditRelease
        uses: irongut/EditRelease@v1.2.0
        with:
          id: ${{ env.RELEASE_ID }}
          token: ${{ secrets.GITHUB_TOKEN }}
          replacebody: true
          files: ${{ env.TEMP_BODY_FILE }}

      - name: Switch Release Status To Full
        if: ${{ !inputs.pre-release }}
        uses: irongut/EditRelease@v1.2.0
        with:
          id: ${{ env.RELEASE_ID }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
