name: Publish on GitHub, CurseForge, Modrinth

# This release workflow can only be triggered manually
on:
  workflow_dispatch:
    inputs:
      jdk-version:
        default: '17'
        required: false
        description: JDK version
        type: string

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: ${{ inputs.jdk-version }}

permissions:
  contents: write

jobs:
  # Test and Build the Mod
  test-and-build:
    uses: ./.github/workflows/build.yml

  todo:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "MINECRAFT_VERSION=$(grep "minecraft_version" gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV
          echo ${{ env.MINECRAFT_VERSION }}