name: Run Unit Test Suite
# pull_request: This workflow will be triggered when new commits are pushed onto GitHub
# ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
# workflow_call: Or it will be triggered by release workflow
# ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call
on: [ pull_request, workflow_call ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Unit Test Suite
        run: ./gradlew :common:test